[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = { version = "0.4.13", features = ["audio"] }
rand = "0.9.0"
serde = { version = "1.0.217", features = ["derive"] }
bincode = "1.3.3"
anyhow = "1.0.95"
display-info = "0.5.4"
